-- Requerimientos Funcionales de Consulta
-- Iteracion 1
-- Grupo B-09


-- RFC1: Mostrar el dinero recibido por cada proveedor durante el año actual y transcurrido
SELECT PP.*, ASW.ID_PROPUESTA, asw."TOTAL GANANCIAS" FROM (

SELECT RE.ID_PROPUESTA AS "ID_PROPUESTA", SUM(RE.COSTO_TOTAL) AS "TOTAL GANANCIAS"
FROM RESERVAS RE
WHERE RE.ID_PROPUESTA IN (
    SELECT PT.ID
    FROM PROPUESTAS PT 
    WHERE PT.ID_PERSONA IN (
        SELECT PEP.ID  
        FROM PERSONAS PEP 
        WHERE ROL = 'operador'
    )
)
GROUP BY RE.ID_PROPUESTA
) ASW
INNER JOIN PROPUESTAS PU
ON PU.ID = ASW.ID_PROPUESTA

INNER JOIN PERSONAS PP
ON PP.ID = PU.ID_PERSONA

ORDER BY asw."TOTAL GANANCIAS" DESC

;


-- RFC2: Mostrar las 20 ofertas más populares
SELECT  *
FROM 
( SELECT ID_PROPUESTA, COUNT(ID_PROPUESTA) AS "Cantidad Reservas"  
FROM RESERVAS 
GROUP BY ID_PROPUESTA
ORDER BY "Cantidad Reservas" DESC)
WHERE ROWNUM <= 20;



-- BONO


-- RFC 3: Indice de ocupacion por inmueble
SELECT R.ID_PROPUESTA, SUM( R.CANTIDAD_PERSONAS), SUM(P.CAPACIDAD_MAXIMA), ( SUM( R.CANTIDAD_PERSONAS) / SUM(P.CAPACIDAD_MAXIMA) ) AS "INDICE"

FROM RESERVAS R
INNER JOIN PROPUESTAS P 
ON R.ID_PROPUESTA = P.ID

GROUP BY R.ID_PROPUESTA
;




-- RFC 4: alohamiento en rago de fechas y servicios
SELECT R.ID_PROPUESTA, R.FECHA_INICIO_ESTADIA, R.DURACION_CONTRATO,
P.ID_APARTAMENTO, P.ID_VIVIENDA_EXPRESS, P.ID_VIVIENDA_UNIVERSITARIA, P.ID_HABITACION

FROM RESERVAS R
INNER JOIN PROPUESTAS P
ON R.ID_PROPUESTA = P.ID

WHERE 
R.FECHA_INICIO_ESTADIA BETWEEN '2018-01-19 21:48:01' AND '2018-01-25 21:48:01'
    AND ( P.ID_HABITACION IN (
        SELECT S.ID_HABITACION FROM SERVICIOS_BASICOS S INNER JOIN TIPOS T ON T.ID = S.ID_TIPO
        WHERE T.NOMBRE = 'baño' OR T.NOMBRE = 'cocina'
    )
    OR P.ID_APARTAMENTO IN (
         SELECT S.ID_APARTAMENTO FROM SERVICIOS_BASICOS S INNER JOIN TIPOS T ON T.ID = S.ID_TIPO
        WHERE T.NOMBRE = 'baño' OR T.NOMBRE = 'cocina'
    )
    OR P.ID_VIVIENDA_EXPRESS IN (
         SELECT S.ID_VIVIENDA_EXPRESS FROM SERVICIOS_BASICOS S INNER JOIN TIPOS T ON T.ID = S.ID_TIPO
        WHERE T.NOMBRE = 'baño' OR T.NOMBRE = 'cocina'
    )
    OR P.ID_VIVIENDA_UNIVERSITARIA IN (
         SELECT S.ID_VIVIENDA_UNIVERSITARIA FROM SERVICIOS_BASICOS S INNER JOIN TIPOS T ON T.ID = S.ID_TIPO
        WHERE T.NOMBRE = 'baño' OR T.NOMBRE = 'cocina'
    )
   
)
;

















