CREATE SEQUENCE seq_id_persona
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_reserva
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_apartamento
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_habitacion
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_hostel
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_hotel
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_hotel_tiene_servicio
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_propuesta
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_servicio_basico
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

-- SERVICIO BASICO HOTELERO
CREATE SEQUENCE seq_id_servicio_hotelero
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_tipo
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_vivienda_express
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

CREATE SEQUENCE seq_id_vivienda_universitaria
MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;