-- RC 7 CONSULTA DEMANDAS


-- por inicio de estadia, mayor demanda ocupacion por mes

-- POR SEMANA MAYOR DEMANDA OCUPACIONAL
SELECT to_number(to_char(to_date(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'),'WW')) AS "SEMANA",  COUNT (to_number(to_char(to_date(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'),'WW'))) AS "CANTIDAD RESERVAS"
FROM RESERVAS R
INNER JOIN PROPUESTAS P ON
R.ID_PROPUESTA = P.ID
WHERE P.TIPO_INMUEBLE = 'Apartamento'
AND ( R.HAY_MULTA IS NULL 
OR R.HAY_MULTA = 0 )
GROUP BY to_number(to_char(to_date(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'),'WW'))
ORDER BY "CANTIDAD RESERVAS" DESC;

-- POR MES MAYOR DEMANDA OCUPACIONAL
SELECT TO_CHAR(TO_DATE(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'), 'Month') AS "MES", COUNT (TO_CHAR(TO_DATE(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'), 'Month')) AS "CANTIDAD RESERVAS"
FROM RESERVAS R
INNER JOIN PROPUESTAS P ON
R.ID_PROPUESTA = P.ID
WHERE UPPER(P.TIPO_INMUEBLE) = UPPER('Apartamento')
AND ( R.HAY_MULTA IS NULL 
OR R.HAY_MULTA = 0 )
GROUP BY TO_CHAR(TO_DATE(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'), 'Month')
ORDER BY "CANTIDAD RESERVAS" DESC;




SELECT * FROM RESERVAS;


-- ahora por suma del total de ingresos por mes

-- POR SEMANA
SELECT to_number(to_char(to_date(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'),'WW')) AS "SEMANA", SUM(R.COSTO_TOTAL) AS "INGRESOS"
FROM RESERVAS R
INNER JOIN PROPUESTAS P ON
R.ID_PROPUESTA = P.ID
WHERE P.TIPO_INMUEBLE = 'Apartamento'
AND ( R.HAY_MULTA IS NULL 
OR R.HAY_MULTA = 0 )
GROUP BY to_number(to_char(to_date(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'),'WW'))
ORDER BY "INGRESOS" DESC;

-- POR MES
SELECT TO_CHAR(TO_DATE(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'), 'Month') AS "MES", SUM(R.COSTO_TOTAL) AS "INGRESOS"
FROM RESERVAS R
INNER JOIN PROPUESTAS P ON
R.ID_PROPUESTA = P.ID
WHERE UPPER(P.TIPO_INMUEBLE) = UPPER('Apartamento')
AND ( R.HAY_MULTA IS NULL 
OR R.HAY_MULTA = 0 )
GROUP BY TO_CHAR(TO_DATE(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'), 'Month')
ORDER BY "INGRESOS" DESC;





-- menor ocupacion
-- POR SEMANA MENOR DEMANDA OCUPACIONAL
SELECT to_number(to_char(to_date(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'),'WW')) AS "SEMANA",  COUNT (to_number(to_char(to_date(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'),'WW'))) AS "CANTIDAD RESERVAS"
FROM RESERVAS R
INNER JOIN PROPUESTAS P ON
R.ID_PROPUESTA = P.ID
WHERE P.TIPO_INMUEBLE = 'Apartamento'
AND ( R.HAY_MULTA IS NULL 
OR R.HAY_MULTA = 0 )
GROUP BY to_number(to_char(to_date(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'),'WW'))
ORDER BY "CANTIDAD RESERVAS" ;

-- POR MES MENOR DEMANDA OCUPACIONAL
SELECT TO_CHAR(TO_DATE(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'), 'Month') AS "MES", COUNT (TO_CHAR(TO_DATE(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'), 'Month')) AS "CANTIDAD RESERVAS"
FROM RESERVAS R
INNER JOIN PROPUESTAS P ON
R.ID_PROPUESTA = P.ID
WHERE UPPER(P.TIPO_INMUEBLE) = UPPER('Apartamento')
AND ( R.HAY_MULTA IS NULL 
OR R.HAY_MULTA = 0 )
GROUP BY TO_CHAR(TO_DATE(R.FECHA_INICIO_ESTADIA,'YYYY-MM-DD HH24:MI:SS'), 'Month')
ORDER BY "CANTIDAD RESERVAS" ;









-- RF 8 CLIENTES FRECUENTES POR ALOJAMIETO DADO ::  ESTE PARA APARTAMENTO
SELECT Q.ID_PERSONA, q."CANTIDAD_RESERVAS", P.NOMBRE, P.APELLIDO, P.TIPO FROM 
(
SELECT R.ID_PERSONA, COUNT(R.ID_PERSONA) AS "CANTIDAD_RESERVAS"
FROM RESERVAS R 
WHERE R.ID_PROPUESTA IN (
    SELECT P.ID FROM PROPUESTAS P WHERE UPPER(P.TIPO_INMUEBLE) = UPPER('apartamento')
) 
AND R.DURACION_CONTRATO >= 15
GROUP BY R.ID_PERSONA 
HAVING COUNT(R.ID_PERSONA) >= 3
ORDER BY "CANTIDAD_RESERVAS" DESC
) Q
JOIN PERSONAS P
ON Q.ID_PERSONA = P.ID;











